Fast fail

diff --git a/.github/workflows/atom-test.yaml b/.github/workflows/atom-test.yaml
--- a/.github/workflows/atom-test.yaml
+++ b/.github/workflows/atom-test.yaml
@@ -107,6 +107,14 @@ jobs:
           docker exec atom_test bash -c \
             "python3 -m atom.examples.simple_inference --model ${{ matrix.model_path }} ${{ matrix.extraArgs }} --temperature 0 | grep -E '^Prompt: |^Completion:'" > atom_test_output.txt
           
+          EXIT_CODE=$?
+          if [ $EXIT_CODE -ne 0 ]; then
+            echo "Test failed."
+            exit 1
+          else
+            echo "Test passed."
+          fi
+          
           echo ""
           echo "========== Showing test output below =========="
           cat atom_test_output.txt
