Temporarily remove 'Clean up old containers'

diff --git a/.github/workflows/atom-vllm-accuracy-validation.yaml b/.github/workflows/atom-vllm-accuracy-validation.yaml
--- a/.github/workflows/atom-vllm-accuracy-validation.yaml
+++ b/.github/workflows/atom-vllm-accuracy-validation.yaml
@@ -1284,14 +1284,14 @@ jobs:
           echo "MODEL_CACHE_MOUNT=${MODEL_CACHE_MOUNT}" >> "$GITHUB_ENV"
           echo "MODEL_CACHE_DESC=${MODEL_CACHE_DESC}" >> "$GITHUB_ENV"
 
-      - name: Clean up old containers
-        if: ${{ steps.validation-window.outputs.should_run == 'true' }}
-        run: |
-          containers=$($CONTAINER_ENGINE ps -q)
-          if [ -n "$containers" ]; then
-            $CONTAINER_ENGINE kill $containers || true
-          fi
-          $CONTAINER_ENGINE rm -f "$CONTAINER_NAME" 2>/dev/null || true
+      #- name: Clean up old containers
+      #  if: ${{ steps.validation-window.outputs.should_run == 'true' }}
+      #  run: |
+      #    containers=$($CONTAINER_ENGINE ps -q)
+      #    if [ -n "$containers" ]; then
+      #      $CONTAINER_ENGINE kill $containers || true
+      #    fi
+      #    $CONTAINER_ENGINE rm -f "$CONTAINER_NAME" 2>/dev/null || true
 
       - name: Start validation container
         if: ${{ steps.validation-window.outputs.should_run == 'true' }}
